export const CHANGE_KEYWORDS = "CHANGE_KEYWORDS"
export const CHANGE_CURINDEX = "CHANGE_CURINDEX"
export const CHANGE_SEARCHRESULT = "CHANGE_SEARCHRESULT"
export const CHANGE_SEARCHSUGGEST = "CHANGE_SEARCHSUGGEST"